# Generated by Django 3.2.9 on 2021-11-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('raw_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(max_length=10)),
                ('discount', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('is_new', models.BooleanField()),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_url', models.TextField(blank=True, null=True)),
                ('codCountry', models.CharField(blank=True, max_length=50, null=True)),
                ('variation_0_color', models.CharField(blank=True, max_length=50, null=True)),
                ('variation_1_color', models.CharField(blank=True, max_length=50, null=True)),
                ('variation_0_thumbnail', models.TextField(blank=True, null=True)),
                ('variation_0_image', models.TextField(blank=True, null=True)),
                ('variation_1_thumbnail', models.TextField(blank=True, null=True)),
                ('variation_1_image', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
